name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy 
    runs-on: ['self-hosted']
    steps:
      - name: Update Odoo
        run: |
          sudo su - egap -c "/home/egap/.local/bin/odoo-update"

